export interface Action {
  REQUEST: string;
  SUCCESS: string;
  FAILURE: string;
}

export const APPLIED_SCHOOL_LIST_ACTION: Action = {
  FAILURE: "APPLIED_SCHOOL_LIST_FAILURE",
  REQUEST: "APPLIED_SCHOOL_LIST_REQUEST",
  SUCCESS: "APPLIED_SCHOOL_LIST_SUCCESS",
};

export const LOADER_ACTION = {
  SET: "SET_LOADER",
  CLEAR: "CLEAR_LOADER",
};

export const LIVE_CONTEST_ACTION: Action = {
  FAILURE: "LIVE_CONTEST_ACTION_FAILURE",
  REQUEST: "LIVE_CONTEST_ACTION_REQUEST",
  SUCCESS: "LIVE_CONTEST_ACTION_SUCCESS",
};

export const JUDGE_ACTION: Action = {
  FAILURE: "JUDGE_ACTION_FAILURE",
  REQUEST: "JUDGE_ACTION_REQUEST",
  SUCCESS: "JUDGE_ACTION_SUCCESS",
};

export const ALL_CONTESTS_ACTION: Action = {
  FAILURE: "ALL_CONTESTS_ACTION_FAILURE",
  REQUEST: "ALL_CONTESTS_ACTION_REQUEST",
  SUCCESS: "ALL_CONTESTS_ACTION_SUCCESS",
};

export const CONTEST_TO_BE_EVALUATED_ACTION = {
  FAILURE: "CONTEST_TO_BE_EVALUATED_FAILURE",
  REQUEST: "CONTEST_TO_BE_EVALUATED_REQUEST",
  SUCCESS: "CONTEST_TO_BE_EVALUATED_SUCCESS",
};

export const STORIES_TO_BE_EVALUATED = {
  FAILURE: "STORIES_TO_BE_EVALUATED_FALIURE",
  REQUEST: "STORIES_TO_BE_EVALUATED_REQUEST",
  SUCCESS: "STORIES_TO_BE_EVALUATED_SUCCESS",
};

export const LIVE_CONTEST_STORIES = {
  FAILURE: "LIVE_CONTEST_STORIES_FAILURE",
  REQUEST: "LIVE_CONTEST_STORIES_REQUEST",
  SUCCESS: "LIVE_CONTEST_STORIES_SUCCESS",
};

export const GET_CONTEST_BY_ID = {
  FAILURE: "GET_CONTEST_BY_ID_FAILURE",
  REQUEST: "GET_CONTEST_BY_ID_REQUEST",
  SUCCESS: "GET_CONTEST_BY_ID_SUCCESS",
};


export const GET_RESTAURANT_DETAILS: Action = {
  FAILURE: "GET_RESTAURANT_DETAILS_FAILURE",
  REQUEST: "GET_RESTAURANT_DETAILS_REQUEST",
  SUCCESS: "GET_RESTAURAN_DETAILS_SUCCESS"
}

export const GET_ALL_MAIN_COURSES = {
  FAILURE: "GET_ALL_MAIN_COURSES_FAILURE",
  REQUEST: "GET_ALL_MAIN_COURSES_REQUEST",
  SUCCESS: "GET_ALL_MAIN_COURSES_SUCCESS"
}

export const GET_ALL_RESTAURANTS = {
  FAILURE: "GET_ALL_RESTAURANTS_FAILURE",
  REQUEST: "GET_ALL_RESTAURANTS_REQUEST",
  SUCCESS: "GET_ALL_RESTAURANTS_SUCCESS"
}

export const GET_ALL_CUISINES = {
  FAILURE: "GET_ALL_CUISINES_FAILURE",
  REQUEST: "GET_ALL_CUISINES_REQUEST",
  SUCCESS: "GET_ALL_CUISINES_SUCCESS"
}